### ISSUE TITLE
Compatibility issue with Antispam Bee

### ISSUE THREAD

**Issue by Zodiac1978** [johndarrel/hide-my-wp#2]
Hi @johndarrel 

We got a support question about making our two plugins compatible:
https://github.com/pluginkollektiv/antispam-bee/issues/585

Before we waste time looking at your code ... maybe you already have a way to help others to be compatible with your plugin. So, what would be the preferred way to get the new path if someone redirect, for example the `wp-comments-post.php`?

Any suggestions?

Thanks in advance!

All the best
Torsten

**Comment by johndarrel** [comment]
Hi,

Yes, after customizing the path, you can simply access the path using 
WordPress home_url function:

home_url('wp-comments-post.php', 'relative');

---
Best,
John D
Hide My WP Ghost
